apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-Deployment
  labels:
    tier: frontend
    app: myapp
spec:
  selector:
    matchLabels:
      app: nginx
      tier: frontend
  replicas: 3
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx
        

  